-standard steps to follow in building classification modles
1. import all necessary library
2. import the data
3. perform EDA on the data
4. split data into predictors and target 
5. Basd on EDA apply data preprocessing
6. feature engineering
7. choose classifier and import it
8. create object from the classifier
9. apply classifier onto the training data
10. check performance on test data by using confusion matrix
11. if performance is not good repeat necessary steps b/w 4-9

In [ ]:
#we can choose array of K values and run algorithm, based on the accuracy of the models we can decide

#KNN implementation

In [ ]:
import numpy as np#
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
Data = pd.read_csv('https://raw.githubusercontent.com/Abeyaantrix2Internship/intern/main/Social_Network_Ads.csv') 
Data.head()
#age and estimated salary columns are features(predictors)
# purchase columns is target

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [ ]:
Data.shape

(400, 5)

In [ ]:
Data.describe()

            User ID         Age  EstimatedSalary   Purchased
count  4.000000e+02  400.000000       400.000000  400.000000
mean   1.569154e+07   37.655000     69742.500000    0.357500
std    7.165832e+04   10.482877     34096.960282    0.479864
min    1.556669e+07   18.000000     15000.000000    0.000000
25%    1.562676e+07   29.750000     43000.000000    0.000000
50%    1.569434e+07   37.000000     70000.000000    0.000000
75%    1.575036e+07   46.000000     88000.000000    1.000000
max    1.581524e+07   60.000000    150000.000000    1.000000

In [ ]:
Data.describe(include='all')

             User ID  Gender         Age  EstimatedSalary   Purchased
count   4.000000e+02     400  400.000000       400.000000  400.000000
unique           NaN       2         NaN              NaN         NaN
top              NaN  Female         NaN              NaN         NaN
freq             NaN     204         NaN              NaN         NaN
mean    1.569154e+07     NaN   37.655000     69742.500000    0.357500
std     7.165832e+04     NaN   10.482877     34096.960282    0.479864
min     1.556669e+07     NaN   18.000000     15000.000000    0.000000
25%     1.562676e+07     NaN   29.750000     43000.000000    0.000000
50%     1.569434e+07     NaN   37.000000     70000.000000    0.000000
75%     1.575036e+07     NaN   46.000000     88000.000000    1.000000
max     1.581524e+07     NaN   60.000000    150000.000000    1.000000

In [ ]:
#split data into predictors and targets
Predictors= Data.iloc[:,2:4]
Target= Data.iloc[:,-1:]
print(Predictors.head())
print(Target.head())

   Age  EstimatedSalary
0   19            19000
1   35            20000
2   26            43000
3   27            57000
4   19            76000
   Purchased
0          0
1          0
2          0
3          0
4          0

In [ ]:
# apply standardization inorder to bring column into same scale
# standardization data is vaey important in classification

In [ ]:
from sklearn.preprocessing import StandardScaler
SS=StandardScaler()
X=SS.fit_transform(Predictors)

In [ ]:
print(X)

In [ ]:
#feature engineering
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test= train_test_split(X, Target,test_size=0.2,random_state=0)
print(X_train.shape,Y_train.shape)
print(X_test.shape,Y_test.shape)

(320, 2) (320, 1)
(80, 2) (80, 1)

In [ ]:
#KNN classifier 
from sklearn.neighbors import KNeighborsClassifier
KNN= KNeighborsClassifier(n_neighbors=3, metric='minkowski',p=2) #When p=2 minikowski becomes euclidian distance
KNN.fit(X_train,Y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

KNeighborsClassifier(n_neighbors=3)

In [ ]:
#now check test data
Y_predicted=KNN.predict(X_test)#Y predicted data from X_test data

In [ ]:
#confusion matrix
from sklearn.metrics import confusion_matrix
CM=confusion_matrix(Y_test,Y_predicted)
print(CM)

[[55  3]
 [ 1 21]]

In [ ]:
Accuracy=((CM[0,0]+CM[1,1])/sum(sum(CM)))*100
print('accuracy of model=',Accuracy,"%")

accuracy of model= 95.0 %

In [ ]:
Precision= (CM[0,0]/(CM[0,0]+CM[1,0]))*100
print('precision of model=',Precision,'%')

precision of model= 98.21428571428571 %

In [ ]:
Recall=(CM[0,0]/(CM[0,0]+CM[0,1]))*100
print('Recall of model=',Recall,'%')

Recall of model= 94.82758620689656 %

In [ ]:
print('F-Score of model=',(2*Precision*Recall/(Precision+Recall)),'%')

F-Score of model= 96.49122807017544 %

In [ ]:
from sklearn.metrics import precision_recall_fscore_support
P,RC,F1,Array= precision_recall_fscore_support(Y_test, Y_predicted)

In [ ]:
print("precesion=",P[0],'\n','Recall=',RC[0],'\n','F-Score=',F1[0])

precesion= 0.9821428571428571
 Recall= 0.9482758620689655
 F-Score= 0.9649122807017544